version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
    depends_on:
      - node

  node:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - kafka

  kafka:
    image: wurstmeister/kafka
    ports:
      - 2181:2181
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: my-topic:1:1
